/**
 * BADGE ICON MAPPING
 * Centralized icon mapping using only Lucide React (tree-shaken)
 * Removes duplicate icon sets for -40kb bundle reduction
 */

import {
  Flame,
  Zap,
  Trophy,
  Lock,
  Crown,
  BookOpen,
  Target,
  Star,
  Video,
  Eye,
  Tv,
  GraduationCap,
  CheckCircle2,
  Sprout,
  Leaf,
  Trees,
  Handshake,
  MessageSquare,
  Users,
  Rocket,
  Medal,
  Heart,
  Sun,
  Moon,
  Award,
  Sparkles
} from 'lucide-react';
import type { LucideIcon } from 'lucide-react';

const ICON_MAP: Record<string, LucideIcon> = {
  '🔥': Flame,
  'flame': Flame,
  'fire': Flame,
  '⚡': Zap,
  'zap': Zap,
  'lightning': Zap,
  '🏆': Trophy,
  'trophy': Trophy,
  '🔒': Lock,
  'lock': Lock,
  'locked': Lock,
  '👑': Crown,
  'crown': Crown,
  '📖': BookOpen,
  'book': BookOpen,
  'script': BookOpen,
  '🎯': Target,
  'target': Target,
  '⭐': Star,
  '🌟': Star,
  'star': Star,
  '🎬': Video,
  'video': Video,
  '👀': Eye,
  'eyes': Eye,
  '📺': Tv,
  'tv': Tv,
  '🎓': GraduationCap,
  'graduation': GraduationCap,
  '✅': CheckCircle2,
  'check': CheckCircle2,
  'tracker': CheckCircle2,
  '🌱': Sprout,
  'seedling': Sprout,
  '🌿': Leaf,
  'herb': Leaf,
  '🌳': Trees,
  'tree': Trees,
  '👋': Handshake,
  'wave': Handshake,
  '💬': MessageSquare,
  'speech': MessageSquare,
  '👥': Users,
  'users': Users,
  'community': Users,
  '🚀': Rocket,
  'rocket': Rocket,
  '🎖️': Medal,
  'medal': Medal,
  '❤️': Heart,
  'heart': Heart,
  '🌅': Sun,
  'sunrise': Sun,
  '🦉': Moon,
  'owl': Moon,
  '🏅': Award,
  'award': Award,
  '✨': Sparkles,
  'sparkles': Sparkles,
  'magic': Sparkles
};

export const getBadgeIcon = (iconName: string): LucideIcon => {
  return ICON_MAP[iconName] || ICON_MAP[iconName.toLowerCase()] || Star;
};
