import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { supabase } from '@/integrations/supabase/client';
import { useAuth } from '@/contexts/AuthContext';
import { toast } from 'sonner';

interface FamilyShare {
  id: string;
  owner_id: string;
  partner_id: string | null;
  partner_email: string;
  invite_code: string;
  status: 'pending' | 'accepted' | 'revoked';
  created_at: string;
  accepted_at: string | null;
  revoked_at: string | null;
}

interface PartnerProfile {
  name: string | null;
  email: string | null;
  photo_url: string | null;
}

export function useFamilyShare() {
  const { user } = useAuth();
  const queryClient = useQueryClient();

  // Fetch user's family share (as owner)
  const { data: myShare, isLoading: isLoadingMyShare } = useQuery({
    queryKey: ['family-share', 'owner', user?.id],
    queryFn: async () => {
      if (!user?.id) return null;
      
      const { data, error } = await supabase
        .from('family_shares')
        .select('*')
        .eq('owner_id', user.id)
        .single();
      
      if (error && error.code !== 'PGRST116') throw error;
      return data as FamilyShare | null;
    },
    enabled: !!user?.id,
  });

  // Fetch share where user is partner
  const { data: partnerOf, isLoading: isLoadingPartnerOf } = useQuery({
    queryKey: ['family-share', 'partner', user?.id],
    queryFn: async () => {
      if (!user?.id) return null;
      
      const { data, error } = await supabase
        .from('family_shares')
        .select('*')
        .eq('partner_id', user.id)
        .eq('status', 'accepted')
        .single();
      
      if (error && error.code !== 'PGRST116') throw error;
      return data as FamilyShare | null;
    },
    enabled: !!user?.id,
  });

  // Fetch partner profile if share is accepted
  const { data: partnerProfile } = useQuery({
    queryKey: ['partner-profile', myShare?.partner_id],
    queryFn: async () => {
      if (!myShare?.partner_id) return null;
      
      const { data, error } = await supabase
        .from('profiles')
        .select('name, email, photo_url')
        .eq('id', myShare.partner_id)
        .single();
      
      if (error) throw error;
      return data as PartnerProfile;
    },
    enabled: !!myShare?.partner_id && myShare?.status === 'accepted',
  });

  // Fetch owner profile if user is partner
  const { data: ownerProfile } = useQuery({
    queryKey: ['owner-profile', partnerOf?.owner_id],
    queryFn: async () => {
      if (!partnerOf?.owner_id) return null;
      
      const { data, error } = await supabase
        .from('profiles')
        .select('name, email, photo_url')
        .eq('id', partnerOf.owner_id)
        .single();
      
      if (error) throw error;
      return data as PartnerProfile;
    },
    enabled: !!partnerOf?.owner_id,
  });

  // Create invite mutation - returns invite_code for email sending
  const createInvite = useMutation({
    mutationFn: async (partnerEmail: string) => {
      if (!user?.id) throw new Error('Not authenticated');
      
      const { data, error } = await supabase
        .from('family_shares')
        .insert({
          owner_id: user.id,
          partner_email: partnerEmail.toLowerCase().trim(),
          invite_code: '', // Will be auto-generated by trigger
        })
        .select('id, invite_code, partner_email')
        .single();
      
      if (error) throw error;
      return data as { id: string; invite_code: string; partner_email: string };
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['family-share'] });
    },
    onError: (error: Error) => {
      if (error.message.includes('unique_owner')) {
        toast.error('You already have an active invite');
      } else {
        toast.error('Failed to create invite');
      }
    },
  });

  // Revoke access mutation
  const revokeAccess = useMutation({
    mutationFn: async () => {
      if (!myShare?.id) throw new Error('No share found');
      
      const { error } = await supabase
        .from('family_shares')
        .update({
          status: 'revoked',
          revoked_at: new Date().toISOString(),
        })
        .eq('id', myShare.id);
      
      if (error) throw error;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['family-share'] });
      toast.success('Access revoked');
    },
    onError: () => {
      toast.error('Failed to revoke access');
    },
  });

  // Delete invite mutation
  const deleteInvite = useMutation({
    mutationFn: async () => {
      if (!myShare?.id) throw new Error('No share found');
      
      const { error } = await supabase
        .from('family_shares')
        .delete()
        .eq('id', myShare.id);
      
      if (error) throw error;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['family-share'] });
      toast.success('Invite deleted');
    },
    onError: () => {
      toast.error('Failed to delete invite');
    },
  });

  // Accept invite mutation
  const acceptInvite = useMutation({
    mutationFn: async (inviteCode: string) => {
      const { data, error } = await supabase
        .rpc('accept_family_invite', { p_invite_code: inviteCode.toUpperCase().trim() });
      
      if (error) throw error;
      
      const result = data as { success: boolean; error?: string; message?: string };
      if (!result.success) {
        throw new Error(result.error || 'Failed to accept invite');
      }
      
      return result;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['family-share'] });
      toast.success('Invite accepted! You now have shared access.');
    },
    onError: (error: Error) => {
      toast.error(error.message || 'Failed to accept invite');
    },
  });

  return {
    // Data
    myShare,
    partnerOf,
    partnerProfile,
    ownerProfile,
    
    // Loading states
    isLoading: isLoadingMyShare || isLoadingPartnerOf,
    
    // Computed
    hasActiveShare: myShare?.status === 'accepted',
    hasPendingInvite: myShare?.status === 'pending',
    isPartner: !!partnerOf,
    
    // Mutations
    createInvite,
    revokeAccess,
    deleteInvite,
    acceptInvite,
  };
}
