
-- SCRIPT 1: TANTRUMS - DEFIANT
INSERT INTO scripts (
  title, category, profile, age_min, age_max,
  the_situation, what_doesnt_work, strategy_steps, why_this_works,
  what_to_expect, common_variations, parent_state_needed, tags, emergency_suitable
) VALUES (
  'Breaks/throws things when angry - destroys toys or household items',
  'Tantrums', 'DEFIANT', 4, 11,
  'Your DEFIANT child is told "no" or experiences frustration, and instead of crying or arguing, they **destroy**. They throw their toy across the room, smash it against the wall, or break household items like remote controls or picture frames. The destruction is deliberate—they watch you as they do it, checking if this will finally make you cave. After the destruction, they may escalate to screaming or rage, or they might go silent and defiant, waiting to see what you''ll do. You''re left standing there with broken items, feeling a mix of anger, shock, and helplessness, wondering if you should punish them, make them pay for it, or just give in to avoid more destruction.',
  '**"If you break that, you''re in BIG trouble!"** → Threat creates a power struggle. Now they MUST break it to prove you can''t control them.

**Yelling and punishing immediately** → They learn: "My destruction gets a huge reaction." The behavior intensifies because the destruction **worked**—it gave them control over your emotional state.

**Making them pay for broken items with allowance** → For DEFIANT kids, this feels like winning. They traded money for power, and they''d do it again.

**Immediately replacing broken toys** → They learn: "Breaking things has no real consequence." Destruction becomes a daily pattern.

**Why these don''t work:**
The DEFIANT brain is wired to seek **control and autonomy**. When they destroy something, they are asking: *"Can I make you change your decision? Can I force you to react?"* Traditional consequences (threats, punishments, immediate reactions) all give them the **answer they want**: "Yes, I can control you." The destruction becomes their most powerful tool.',
  '[{"step_number":1,"title":"Calm, neutral acknowledgment of the destruction","explanation":"When they break or throw something, you do NOT react with shock, anger, or threats. You say in a completely **calm, factual tone**: \n\n→ **\"You broke the [item]. That''s disappointing.\"** \n→ Then you turn and **walk away**. \n\nYou do NOT:\n• Yell or lecture\n• Threaten punishment \n• Engage in a power struggle\n• Ask \"Why did you do that?!\"\n\nThe DEFIANT child is **watching for your reaction**. If you explode, they win—they controlled you. If you stay calm and factual, they experience something unfamiliar: their destruction didn''t work.","example_phrases":["\"You broke the remote. That''s disappointing.\"","\"You threw your toy and it broke. I see that.\"","\"The picture frame is broken. That''s unfortunate.\""]},{"step_number":2,"title":"Natural consequence: The broken item is gone","explanation":"Later (NOT in the heat of the moment), you explain the **natural consequence** in a calm, matter-of-fact tone:\n\n→ **\"The [item] is broken, so we don''t have it anymore. I won''t be replacing it.\"**\n\nIf it was their toy: **\"Your [toy] is broken. I won''t buy a new one. If you want another one, you can save your allowance.\"**\n\nIf it was a household item (remote, picture frame): **\"The remote is broken. We''ll have to walk to the TV to change channels until I can afford a new one.\"**\n\nYou are NOT punishing them—you are simply implementing **reality**: broken things don''t work, and replacement isn''t automatic. You say this with the same tone you''d use to say \"We''re out of milk.\"","example_phrases":["\"The remote is broken. We''ll walk to the TV to change channels now.\"","\"Your toy is broken. I won''t replace it. If you want another, you can save your money.\"","\"The picture frame broke. We won''t have that picture on the wall anymore.\""]},{"step_number":3,"title":"Future prevention: Pre-teach the ''destroy box''","explanation":"Once they''re calm (hours or days later), you introduce a **healthier outlet** for destructive urges:\n\n→ **\"Sometimes when we''re really angry, we want to break or throw things. I get that. So we''re going to make a ''destroy box.''\"**\n\nYou create a box filled with **items that are OK to destroy**: \n• Cardboard boxes they can stomp\n• Paper they can rip \n• Plastic bottles they can crush\n• Ice cubes they can smash outside\n\nYou explain: **\"If you feel like breaking something, you can use the destroy box. But toys and household items are NOT for breaking. If you break them, they''re gone.\"**\n\nThis gives them **control and autonomy** (they CAN destroy things) while protecting what matters.","example_phrases":["\"When you''re really mad, you can destroy things from this box. Not your toys or our stuff.\"","\"If you need to break something, grab the destroy box. That''s what it''s for.\"","\"You''re allowed to be destructive—but only with destroy box items.\""]}]'::jsonb,
  '**Neurologically, DEFIANT children have:**
• **Underdeveloped prefrontal cortex** (poor impulse control under stress)
• **Hyperactive amygdala** (intense emotional responses to perceived control)
• **Low frustration tolerance** combined with high need for autonomy

When they destroy things, their brain is asking: *"Can I control you with this behavior?"*

**Traditional consequences (yelling, punishments, immediate reactions) all answer "YES"**—because they successfully controlled your emotional state. The destruction becomes their most powerful tool.

**This strategy works because:**
1. **Calm, factual response** → Removes the reward (your big reaction)
2. **Natural consequence** → They experience reality (broken = gone) without a power struggle
3. **Destroy box** → Gives them healthy control and autonomy over destructive urges

You''re teaching: *"You can''t control me with destruction, but you CAN control your own need to destroy—in a healthy way."*

The destruction stops when it stops **working**.',
  '{"first_30_seconds":"They will likely escalate briefly when you walk away calmly—they expected a big reaction. They might break something else, scream, or follow you demanding engagement. Stay calm and repeat: \"I see you''re angry. I''ll talk when you''re calm.\"","by_90_seconds":"Most DEFIANT kids will de-escalate once they realize the destruction isn''t giving them power. They may retreat to their room or go silent.","this_is_success":"Success is NOT that they never break things again immediately. Success is that they experience a consequence (broken = gone) WITHOUT a power struggle, and over time, destruction decreases because it no longer ''works.''","timeline_to_change":"Expect 2-4 weeks of testing. They WILL break things again to see if you stay calm. Each time you implement the calm consequence, you''re rewiring their brain: \"Destruction doesn''t control Mom/Dad.\"","dont_expect":["Immediate remorse or apology after breaking things—DEFIANT kids rarely apologize in the moment","Them to stop breaking things after one calm consequence—they will test the boundary multiple times","Them to use the destroy box immediately—it takes time to build this new habit","Perfect behavior—some destruction is normal for DEFIANT brains under high stress"]}'::jsonb,
  '[{"scenario":"They break something, then demand you fix it or replace it immediately","response":"Stay calm and factual: \"It''s broken. I won''t be replacing it.\" Do NOT argue or explain further. If they rage, use silent presence (stay nearby but don''t engage). The natural consequence stands."},{"scenario":"They destroy something expensive (iPad, TV remote, sibling''s toy)","response":"Same calm response: \"The [item] is broken. That''s really disappointing.\" For expensive items, add: \"I won''t be able to replace that for a long time.\" Then let them experience the long-term consequence (no iPad for months). For sibling''s toys, they owe their sibling a replacement from their own money/belongings."},{"scenario":"They ignore the destroy box and continue breaking household items","response":"Don''t force the destroy box—it''s an OFFER of control, not a rule. Continue implementing natural consequences for household items. Over time, as destruction stops ''working,'' they may gravitate toward the destroy box as a healthier outlet."},{"scenario":"They break something in public (store, friend''s house)","response":"Same calm response in public: \"You broke the [item]. We''ll need to pay for that/replace it.\" Then leave immediately if possible. Later, implement consequence: \"You broke [item] at the store. You''ll need to pay for it from your allowance/do extra chores.\""}]'::jsonb,
  'Calm, detached, factual. You must be the **calm enforcer of reality**—not angry at the destruction, not shocked, not in a power struggle, just calmly implementing natural consequences. The DEFIANT child needs to feel that destruction has real consequences (broken = gone) but does NOT give them power over you.',
  ARRAY['tantrums','defiant','destruction','breaking-things','throwing','property-damage','natural-consequences','destroy-box'],
  false
);

-- SCRIPT 2: HYGIENE - DEFIANT  
INSERT INTO scripts (
  title, category, profile, age_min, age_max,
  the_situation, what_doesnt_work, strategy_steps, why_this_works,
  what_to_expect, common_variations, parent_state_needed, tags, emergency_suitable
) VALUES (
  'Refuses to brush teeth - fights and runs away every night',
  'Hygiene', 'DEFIANT', 3, 10,
  'Bedtime is approaching, and you announce it''s time to brush teeth. Your DEFIANT child immediately **refuses**—they say "No," run away, hide in their room, or physically resist when you try to guide them to the bathroom. If you try to force it, they clench their mouth shut, turn their head away, or have a full meltdown. This battle happens **every single night**, turning a 2-minute task into a 20-minute power struggle. You''re exhausted, worried about cavities, and frustrated that something so simple has become a nightly war. You oscillate between forcing it (which feels awful) and giving up (which feels irresponsible).',
  '**"If you don''t brush your teeth, you''ll get cavities!"** → Future consequences mean nothing to young DEFIANT brains. They don''t care about cavities in 6 months—they care about control RIGHT NOW.

**Bribing them:** "If you brush, you can have extra screen time" → Teaches them to hold hygiene hostage. Next time, they''ll demand bigger bribes.

**Physically forcing the toothbrush in their mouth** → Creates trauma, intensifies defiance, and teaches them that their body autonomy doesn''t matter. The power struggle escalates.

**Giving up and skipping it** → They learn: "If I fight hard enough, I win." Defiance becomes their most powerful tool, and hygiene suffers.

**Why these don''t work:**
The DEFIANT brain is wired to resist **perceived control**. When you say "Brush your teeth," they hear "I''m controlling your body." Their refusal isn''t about the toothbrush—it''s about **autonomy**. Traditional approaches (threats, bribes, force) all reinforce the power struggle, making them more determined to resist.',
  '[{"step_number":1,"title":"Offer controlled autonomy: Two brushing choices","explanation":"Before bedtime (during calm time), you present **two acceptable choices**:\n\n→ **\"Tonight you can brush your teeth in the bathroom OR in the living room. Your choice.\"**\n→ **\"You can use the blue toothbrush OR the red toothbrush. Which one?\"**\n→ **\"You can brush before pajamas OR after pajamas. You decide.\"**\n\nYou are NOT asking IF they will brush—you''re giving them control over HOW. The DEFIANT brain craves autonomy, so you give it to them within **your non-negotiable boundary** (teeth WILL be brushed).","example_phrases":["\"Brushing time is coming. Do you want to brush in the bathroom or the living room?\"","\"Blue toothbrush or red toothbrush tonight?\"","\"Before pajamas or after pajamas? You choose.\""]},{"step_number":2,"title":"The 2-minute timer ritual","explanation":"To remove the power struggle over **how long** brushing takes, you introduce a **visual timer**:\n\n→ **\"When the timer goes off, brushing is done. You can brush yourself, or I can help. Your choice.\"**\n\nSet a 2-minute timer where they can SEE it (phone, kitchen timer, visual timer). The timer becomes the ''boss,'' not you. This removes you from the enforcement role.\n\nIf they refuse to brush during the timer: **\"Timer is running. If you don''t brush, I''ll brush for you when it beeps.\"** (Calm, factual, not a threat.)\n\nIf they brush themselves (even poorly): **\"You did it yourself! Great job.\"** Do NOT critique their technique in the moment—that re-ignites the power struggle.","example_phrases":["\"The timer is the boss, not me. When it beeps, brushing is done.\"","\"You can brush yourself, or I can help. Timer decides when we''re finished.\"","\"Look, the timer is going! Let''s see if you can beat it.\""]},{"step_number":3,"title":"Natural consequence for refusal: Parent brushing","explanation":"If they refuse to brush during the timer, you calmly implement the consequence:\n\n→ **\"Timer went off. You didn''t brush, so I''m brushing for you now.\"**\n\nYou do this with **calm, mechanical efficiency**—NOT as punishment, but as a fact. You gently but firmly brush their teeth (front teeth only if they resist hard). Keep it under 30 seconds.\n\nYou are NOT angry. You are NOT in a power struggle. You are simply implementing reality: *\"Teeth get brushed. You can do it, or I will. Your choice.\"*\n\nOver time, most DEFIANT kids choose to brush themselves to avoid parent brushing—they regain autonomy by cooperating.","example_phrases":["\"You chose not to brush, so I''m doing it now. Next time, you can do it yourself.\"","\"I know you don''t like me brushing. Tomorrow you can do it yourself if you beat the timer.\"","\"All done. Tomorrow, try brushing yourself so I don''t have to.\""]}]'::jsonb,
  '**Neurologically, DEFIANT children have:**
• **Hyperactive amygdala** (intensely threatened by perceived loss of control)
• **Underdeveloped prefrontal cortex** (poor impulse control, can''t think about future consequences like cavities)
• **High need for autonomy** (their brain MUST feel in control of their own body)

When you say "Brush your teeth," their brain interprets it as: *"You''re controlling my body."* Their refusal is a **neurological response** to perceived threat, not defiance for defiance''s sake.

**This strategy works because:**
1. **Controlled choices** → Satisfies their need for autonomy (they choose how, where, which brush)
2. **Timer as enforcer** → Removes you from the power struggle (timer is the ''boss'')
3. **Natural consequence** → Parent brushing is reality-based, not punishment, and motivates them to cooperate to regain autonomy

You''re teaching: *"You have control over HOW this happens, but teeth WILL be brushed. You can do it yourself (autonomy) or I will do it (loss of autonomy)."*

The resistance stops when they realize they have **more control** by cooperating than by fighting.',
  '{"first_30_seconds":"When you first introduce the choices, they may refuse both options and say \"I''m NOT brushing!\" Stay calm and repeat: \"These are the two choices. Which one do you pick?\" If they refuse, say: \"Okay, I''ll choose for you. We''re brushing in the bathroom.\"","by_90_seconds":"If they continue to refuse during the timer, calmly implement parent brushing. Expect resistance the first few times—they''re testing if you''ll cave. Stay calm, brush quickly (30 seconds max), and end it.","this_is_success":"Success is NOT perfect toothbrushing immediately. Success is completing the task (even if you brush for them) WITHOUT a 20-minute power struggle. Over time, they will choose to brush themselves to regain autonomy.","timeline_to_change":"Expect 1-2 weeks of testing. The first 3-5 nights, they may refuse both choices and force you to brush for them. By week 2, most DEFIANT kids start choosing to brush themselves because they realize parent brushing means LESS control.","dont_expect":["Perfect brushing technique immediately—they may brush sloppily just to ''do it themselves''","Them to stop resisting after one night—DEFIANT kids will test the boundary multiple times","Cheerful cooperation—they may brush themselves but grumble the whole time (that''s still success)","Instant love of toothbrushing—the goal is compliance, not enthusiasm"]}'::jsonb,
  '[{"scenario":"They choose a toothbrush/location, then refuse to actually brush","response":"Calmly say: \"You picked the blue brush and the bathroom. Timer is starting now.\" Start the timer. If they still refuse when timer beeps, implement parent brushing: \"You didn''t brush, so I''m doing it now.\""},{"scenario":"They brush for 5 seconds and say ''Done!''","response":"Point to the timer: \"Timer says we still have 1 minute and 55 seconds. Keep brushing until it beeps, or I''ll help.\" The timer is the enforcer, not you."},{"scenario":"They physically run away and hide when you start the timer","response":"Calmly go to where they are. Say: \"Timer is still running. You can brush yourself or I will when it beeps.\" If they refuse, calmly carry them to the bathroom and brush for them (30 seconds, front teeth). No anger, no lecture—just implement the consequence."},{"scenario":"They cry and say ''You''re hurting me!'' during parent brushing","response":"Stay calm and gentle but firm. Say: \"I''m being gentle. Next time, you can do it yourself.\" Complete the brushing quickly (30 seconds) and end it. Do NOT let the accusation make you stop—that teaches them crying gets them out of it."},{"scenario":"They cooperate one night, then refuse again the next night","response":"This is normal testing. Don''t react with frustration. Just re-implement the system: \"Do you want the blue brush or red brush tonight?\" Stay consistent—the pattern will stabilize over 1-2 weeks."}]'::jsonb,
  'Calm, robotic, mechanical. You must be the **calm hygiene system administrator**—not frustrated by refusal, not in a debate, not angry during parent brushing, just calmly implementing the reality that teeth get brushed. The DEFIANT child needs to feel that brushing is an immovable routine, and they have autonomy over HOW it happens, not IF.',
  ARRAY['hygiene','defiant','toothbrushing','bedtime-routine','autonomy','timer','natural-consequences','body-autonomy'],
  false
);
