-- Refatoração Script 1: Monday morning school refusal (DEFIANT)
UPDATE scripts SET
  what_doesnt_work = E'You''ve been here before. Many Monday mornings, actually.\n\nYou try the reasonable approach first: "Come on, buddy, you''ll see your friends." He doesn''t even look up. Arms tighter.\n\nThen logic: "You''ll get behind in math." He shrugs. "Don''t care."\n\nThen threats materialize—screen time, dessert, the birthday party next weekend. Each threat bounces off like you''re speaking a foreign language. His jaw sets harder.\n\nYou try pulling the blanket. He grips it like his life depends on it.\n\nYou raise your voice. He raises his.\n\nYou''re now running 12 minutes late. Your coffee is cold. Your patience is gone. And he hasn''t moved an inch from that bed.\n\nThe harder you push, the more concrete he becomes.',
  
  why_this_works = E'Here''s what''s actually happening in his brain right now: he''s not being difficult—he''s being defensive.\n\nWhen a child with this wiring faces something they can''t control (school, Monday, authority), their entire system shifts into "protect mode." Every demand you make gets filtered as a threat. Every push triggers a counter-push.\n\nIt''s not rational. It''s primal.\n\nThe script works because it does something counterintuitive: it stops the war before negotiating peace. You can''t reason with someone in battle stance. You have to help them lower their shield first.\n\nBy naming what''s hard ("Mondays feel heavy"), you become an ally instead of an enemy. By offering micro-choices ("socks or shoes first?"), you give control back without giving up the destination.\n\nHe doesn''t need to win. He needs to not lose.'
WHERE id = 'ab2b3126-ae74-4643-bf55-a032704a1000';

-- Refatoração Script 2: Homework explosion (INTENSE)
UPDATE scripts SET
  what_doesnt_work = E'The worksheet looked simple enough. Ten problems. Maybe fifteen minutes of work.\n\nBut by problem three, something shifted. Her handwriting got bigger. Messier. She erased so hard she tore the paper.\n\nYou offered help. "I DON''T NEED HELP!" The pencil flew. The paper crumpled into a ball.\n\nYou tried staying calm: "Let''s take a breath." She screamed louder.\n\nYou tried firmness: "We don''t throw things." She threw her water bottle.\n\nYou tried walking away. She followed you, still screaming, because now she''s upset AND abandoned.\n\nYou tried sitting with her silently. She told you your breathing was annoying.\n\nEvery response—soft or firm, present or absent—seemed to make it worse. Because by the time she''s throwing things, she''s not choosing her behavior anymore. She''s being hijacked by it.',
  
  why_this_works = E'When frustration hits a certain threshold in an intense child, something biological happens. The part of her brain that plans, reasons, and regulates literally goes offline. She''s not "choosing" to tantrum—she''s flooded.\n\nThink of it like this: her emotional gas tank went from half-full to overflowing in seconds. And now it''s spilling everywhere.\n\nThe script works because it addresses the flood, not the homework.\n\nStep one stops the bleeding (sensory anchor, not words). Step two names what happened without judgment (externalization—"the frustration monster"). Step three bridges back to the task only after she''s regulated.\n\nYou''re not rewarding the explosion. You''re teaching her that big feelings don''t mean everything is ruined. The homework will still get done—just not while she''s drowning.'
WHERE id = 'e7791c56-0197-4f91-b6df-877bf43316a8';