-- 1. Create 3 new video collections (correct columns: name, slug, description, icon_name, display_order)
INSERT INTO video_collections (name, description, slug, icon_name, display_order) VALUES
('Baby & Toddler Sleep', 'Stop the zombie mode. Real solutions for sleep deprivation.', 'baby-sleep', 'Moon', 6),
('Potty Training', 'Ditch the diapers quickly and cleanly.', 'potty-training', 'Baby', 7),
('Fussy Eating', 'From throwing food to tasting veggies.', 'fussy-eating', 'Apple', 8);

-- 2. Insert all 30 videos with auto-generated thumbnails
-- Category: Discipline -> parenting-foundations
INSERT INTO bonuses (title, description, category, thumbnail, view_url, tags, is_new, locked, collection_id) VALUES
('How to Handle Toddler Hitting | Tips from a Pediatrician', 'Direct, medical advice on physical aggression from PedsDocTalk.', 'video', 'https://img.youtube.com/vi/eZqDfSH5KMs/hqdefault.jpg', 'https://www.youtube.com/watch?v=eZqDfSH5KMs', ARRAY['discipline', 'hitting', 'toddler', 'pediatrician'], true, false, (SELECT id FROM video_collections WHERE slug = 'parenting-foundations')),
('Child Psychology: How to Discipline a Child That Does Not Listen', 'Classic, psychology-based approach to defiance from eHowEducation.', 'video', 'https://img.youtube.com/vi/zgkgfliYUCs/hqdefault.jpg', 'https://www.youtube.com/watch?v=zgkgfliYUCs', ARRAY['discipline', 'defiance', 'psychology'], true, false, (SELECT id FROM video_collections WHERE slug = 'parenting-foundations')),
('How To Get Toddler To Stop Hitting', 'Focuses specifically on the hitting behavior with actionable steps from Live On Purpose TV.', 'video', 'https://img.youtube.com/vi/Uny7obNleVk/hqdefault.jpg', 'https://www.youtube.com/watch?v=Uny7obNleVk', ARRAY['discipline', 'hitting', 'toddler'], true, false, (SELECT id FROM video_collections WHERE slug = 'parenting-foundations')),
('Use this Method to Get Your Child to Listen and Behave', 'Hospital-backed advice from St. Louis Children''s Hospital.', 'video', 'https://img.youtube.com/vi/99sBluziPSQ/hqdefault.jpg', 'https://www.youtube.com/watch?v=99sBluziPSQ', ARRAY['discipline', 'listening', 'behavior'], true, false, (SELECT id FROM video_collections WHERE slug = 'parenting-foundations')),
('Gentle Parenting discipline. 7 things to consider', 'Corrects common misconceptions about gentle parenting from Marcela Collier.', 'video', 'https://img.youtube.com/vi/OkCJWDbgXrE/hqdefault.jpg', 'https://www.youtube.com/watch?v=OkCJWDbgXrE', ARRAY['discipline', 'gentle-parenting'], true, false, (SELECT id FROM video_collections WHERE slug = 'parenting-foundations'));

-- Category: Sleep -> baby-sleep
INSERT INTO bonuses (title, description, category, thumbnail, view_url, tags, is_new, locked, collection_id) VALUES
('How to Use the Ferber Method for Sleep Training', 'The gold standard explanation of the most effective method from Parents.', 'video', 'https://img.youtube.com/vi/XVV4WCnqFA8/hqdefault.jpg', 'https://www.youtube.com/watch?v=XVV4WCnqFA8', ARRAY['sleep', 'ferber', 'sleep-training'], true, false, (SELECT id FROM video_collections WHERE slug = 'baby-sleep')),
('Different Sleep Training Methods | Dr. Amna Husain', 'A pediatrician breaking down options so parents can choose without guilt.', 'video', 'https://img.youtube.com/vi/NsIAJp9diB8/hqdefault.jpg', 'https://www.youtube.com/watch?v=NsIAJp9diB8', ARRAY['sleep', 'sleep-training', 'pediatrician'], true, false, (SELECT id FROM video_collections WHERE slug = 'baby-sleep')),
('Baby sleep training #cryitout #pediatrician', 'Short validation from a doctor about CIO safety from Dr. Niky, MD.', 'video', 'https://img.youtube.com/vi/0suxOnNcd3Y/hqdefault.jpg', 'https://www.youtube.com/watch?v=0suxOnNcd3Y', ARRAY['sleep', 'cry-it-out', 'pediatrician'], true, false, (SELECT id FROM video_collections WHERE slug = 'baby-sleep')),
('No-Cry or Gentle to Extinction sleep training methods', 'Comprehensive comparison for parents on the fence from Baby Sleep Trainer.', 'video', 'https://img.youtube.com/vi/pLvP47kKKCg/hqdefault.jpg', 'https://www.youtube.com/watch?v=pLvP47kKKCg', ARRAY['sleep', 'gentle-sleep', 'extinction'], true, false, (SELECT id FROM video_collections WHERE slug = 'baby-sleep')),
('Sleep Training Explained: Ferber, CIO, and Gentle Methods', 'Nurse Practitioner perspective, very reassuring from Just Ask Jen NP.', 'video', 'https://img.youtube.com/vi/WpaFEVpAUtI/hqdefault.jpg', 'https://www.youtube.com/watch?v=WpaFEVpAUtI', ARRAY['sleep', 'ferber', 'cio', 'gentle'], true, false, (SELECT id FROM video_collections WHERE slug = 'baby-sleep'));

-- Category: Tantrums -> managing-emotions
INSERT INTO bonuses (title, description, category, thumbnail, view_url, tags, is_new, locked, collection_id) VALUES
('The Easy Way to Dramatically Reduce Toddler Tantrums', 'Emma Hubbard''s advice on transitions is gold.', 'video', 'https://img.youtube.com/vi/vaGT_FtWEQU/hqdefault.jpg', 'https://www.youtube.com/watch?v=vaGT_FtWEQU', ARRAY['tantrums', 'toddler', 'transitions'], true, false, (SELECT id FROM video_collections WHERE slug = 'managing-emotions')),
('HOW TO STOP TANTRUMS FOREVER! (3 Easy Steps)', 'Solid behavioral modification advice from Dr. Paul.', 'video', 'https://img.youtube.com/vi/rXgz7f2eV3E/hqdefault.jpg', 'https://www.youtube.com/watch?v=rXgz7f2eV3E', ARRAY['tantrums', 'behavior', 'steps'], true, false, (SELECT id FROM video_collections WHERE slug = 'managing-emotions')),
('STOP Talking When Your Child Melts Down. Do THIS Instead', 'Counter-intuitive advice that works instantly from Emma Hubbard.', 'video', 'https://img.youtube.com/vi/9vhawjLEtSw/hqdefault.jpg', 'https://www.youtube.com/watch?v=9vhawjLEtSw', ARRAY['tantrums', 'meltdowns', 'communication'], true, false, (SELECT id FROM video_collections WHERE slug = 'managing-emotions')),
('Handling Tantrums in Young Children and Toddlers', 'Psychotherapist view on emotional regulation from Erica Komisar, LCSW.', 'video', 'https://img.youtube.com/vi/J3eEj6W_1-I/hqdefault.jpg', 'https://www.youtube.com/watch?v=J3eEj6W_1-I', ARRAY['tantrums', 'emotional-regulation', 'therapy'], true, false, (SELECT id FROM video_collections WHERE slug = 'managing-emotions')),
('Managing Child Meltdowns & Tantrums', 'Great for neurodivergent kids but applicable to all intense tantrums from The Autism Helper.', 'video', 'https://img.youtube.com/vi/cv9U_VBTWas/hqdefault.jpg', 'https://www.youtube.com/watch?v=cv9U_VBTWas', ARRAY['tantrums', 'meltdowns', 'neurodivergent'], true, false, (SELECT id FROM video_collections WHERE slug = 'managing-emotions'));

-- Category: Potty -> potty-training
INSERT INTO bonuses (title, description, category, thumbnail, view_url, tags, is_new, locked, collection_id) VALUES
('Potty Training In Days, Not Weeks (8 Essential Steps)', 'Aligns perfectly with the speed promise from Emma Hubbard.', 'video', 'https://img.youtube.com/vi/FuEOVu6U4CI/hqdefault.jpg', 'https://www.youtube.com/watch?v=FuEOVu6U4CI', ARRAY['potty', 'training', 'fast'], true, false, (SELECT id FROM video_collections WHERE slug = 'potty-training')),
('3 DAY POTTY TRAINING METHOD 101', 'A viral, real-life mom vlog showing the gritty reality from Gabriela Terese.', 'video', 'https://img.youtube.com/vi/PXFcSSeG2_g/hqdefault.jpg', 'https://www.youtube.com/watch?v=PXFcSSeG2_g', ARRAY['potty', '3-day', 'real-life'], true, false, (SELECT id FROM video_collections WHERE slug = 'potty-training')),
('Three Day Potty Training Method', 'Clear, structured guide on the method from Actively Family.', 'video', 'https://img.youtube.com/vi/RXxB4ym7jzo/hqdefault.jpg', 'https://www.youtube.com/watch?v=RXxB4ym7jzo', ARRAY['potty', '3-day', 'guide'], true, false, (SELECT id FROM video_collections WHERE slug = 'potty-training')),
('WHAT I WISH I HAD KNOWN BEFORE POTTY TRAINING', 'Addresses the objections parents have from Meg''s Cozy Cottage.', 'video', 'https://img.youtube.com/vi/WwMbZ5o7VP0/hqdefault.jpg', 'https://www.youtube.com/watch?v=WwMbZ5o7VP0', ARRAY['potty', 'tips', 'mistakes'], true, false, (SELECT id FROM video_collections WHERE slug = 'potty-training')),
('Potty training in 3 days - What has worked best?', 'Quick, reputable media source overview from Today''s Parent.', 'video', 'https://img.youtube.com/vi/LcUzZFauDmw/hqdefault.jpg', 'https://www.youtube.com/watch?v=LcUzZFauDmw', ARRAY['potty', '3-day', 'overview'], true, false, (SELECT id FROM video_collections WHERE slug = 'potty-training'));

-- Category: Eating -> fussy-eating
INSERT INTO bonuses (title, description, category, thumbnail, view_url, tags, is_new, locked, collection_id) VALUES
('The Top 7 Mistakes That Make Picky Eating Worse', 'Focuses on what parents are doing wrong from Emma Hubbard.', 'video', 'https://img.youtube.com/vi/pCXF1_f401U/hqdefault.jpg', 'https://www.youtube.com/watch?v=pCXF1_f401U', ARRAY['eating', 'picky', 'mistakes'], true, false, (SELECT id FROM video_collections WHERE slug = 'fussy-eating')),
('This is How You Get Toddlers to Eat ANYTHING', 'Strong promise, practical tips on exposure from Emma Hubbard.', 'video', 'https://img.youtube.com/vi/5oiWWuPFoDw/hqdefault.jpg', 'https://www.youtube.com/watch?v=5oiWWuPFoDw', ARRAY['eating', 'toddler', 'exposure'], true, false, (SELECT id FROM video_collections WHERE slug = 'fussy-eating')),
('Is Your Kid a Picky Eater? Do This...', 'A health-focused perspective on nutrition from Dr. Eric Berg DC.', 'video', 'https://img.youtube.com/vi/BoomsBmRGbg/hqdefault.jpg', 'https://www.youtube.com/watch?v=BoomsBmRGbg', ARRAY['eating', 'picky', 'nutrition'], true, false, (SELECT id FROM video_collections WHERE slug = 'fussy-eating')),
('Toddler Won''t Eat Anything You Make? Here''s what to do', 'Expert dietitian advice for the refusal phase from Mama Knows Nutrition.', 'video', 'https://img.youtube.com/vi/--nuz7MVaHk/hqdefault.jpg', 'https://www.youtube.com/watch?v=--nuz7MVaHk', ARRAY['eating', 'refusal', 'dietitian'], true, false, (SELECT id FROM video_collections WHERE slug = 'fussy-eating')),
('6 Tips for the Toddler Who Refuses to Eat', 'Specific tactics for the stubborn refuser from Jill Castle.', 'video', 'https://img.youtube.com/vi/uq6VvV9Am0Q/hqdefault.jpg', 'https://www.youtube.com/watch?v=uq6VvV9Am0Q', ARRAY['eating', 'refusal', 'tips'], true, false, (SELECT id FROM video_collections WHERE slug = 'fussy-eating'));

-- Category: Screens -> understanding-development
INSERT INTO bonuses (title, description, category, thumbnail, view_url, tags, is_new, locked, collection_id) VALUES
('Screen Time is DESTROYING Children''s Brains | Dr. Daniel Amen', 'Dr. Amen is a huge authority on brain health. Very persuasive.', 'video', 'https://img.youtube.com/vi/mQOBK3W2-70/hqdefault.jpg', 'https://www.youtube.com/watch?v=mQOBK3W2-70', ARRAY['screens', 'brain', 'development'], true, false, (SELECT id FROM video_collections WHERE slug = 'understanding-development')),
('Ground-breaking look at the impact of screen time on kids'' brains', 'Mainstream news validation of the problem from TODAY.', 'video', 'https://img.youtube.com/vi/kaDdqjZumZw/hqdefault.jpg', 'https://www.youtube.com/watch?v=kaDdqjZumZw', ARRAY['screens', 'brain', 'news'], true, false, (SELECT id FROM video_collections WHERE slug = 'understanding-development')),
('Screens May Affect Your Child''s Brain Development', 'Short, shareable, high-authority clip from NBC News.', 'video', 'https://img.youtube.com/vi/ndOB-vXwXxM/hqdefault.jpg', 'https://www.youtube.com/watch?v=ndOB-vXwXxM', ARRAY['screens', 'brain', 'development'], true, false, (SELECT id FROM video_collections WHERE slug = 'understanding-development')),
('Consequences for kids'' of endless screen time', 'Addresses the post-pandemic screen addiction reality from ABC News.', 'video', 'https://img.youtube.com/vi/6bCCDGZyC0I/hqdefault.jpg', 'https://www.youtube.com/watch?v=6bCCDGZyC0I', ARRAY['screens', 'addiction', 'pandemic'], true, false, (SELECT id FROM video_collections WHERE slug = 'understanding-development')),
('How does screen time impact children''s brain development?', 'Harvard authority on the topic from Harvard T.H. Chan School.', 'video', 'https://img.youtube.com/vi/O2SZwMqzWEI/hqdefault.jpg', 'https://www.youtube.com/watch?v=O2SZwMqzWEI', ARRAY['screens', 'brain', 'harvard'], true, false, (SELECT id FROM video_collections WHERE slug = 'understanding-development'));