-- Refatoração Script 3: Refuses to try new skill (INTENSE + Learning)
UPDATE scripts SET
  what_doesnt_work = E'She wanted to learn to ride a bike. Really wanted it. Picked out the helmet herself.\n\nBut then she wobbled. Once. Fell—barely scraped her knee.\n\nAnd it was over.\n\n"I CAN''T DO IT. I''LL NEVER DO IT." The bike is now the enemy. The helmet is across the yard. She''s sitting on the grass, arms wrapped around her knees, refusing to look at you.\n\nYou try encouragement: "Everyone falls at first!" She covers her ears.\n\nYou try logic: "You learned to swim, remember?" "THAT WAS DIFFERENT."\n\nYou try demonstration—you ride in circles, make it look easy. She turns her back.\n\nYou try bribes, consequences, leaving her alone, staying close. Each attempt makes her dig in deeper.\n\nShe''s not scared of falling anymore. She''s scared of trying and failing again in front of you.',
  
  why_this_works = E'For an intense child, failure doesn''t feel like a step toward learning. It feels like evidence of who they are.\n\nOne wobble becomes "I''m bad at bikes." One wrong answer becomes "I''m stupid." The intensity that makes them passionate about things also makes setbacks feel catastrophic.\n\nThey''re not being dramatic. Inside, they genuinely experience small failures as big defeats.\n\nThis script works by separating the child from the failure. Instead of "you can do it" (which she doesn''t believe), you acknowledge what''s hard. Instead of pushing forward, you step sideways—offering a related micro-win that rebuilds confidence without the pressure of the Big Scary Thing.\n\nShe doesn''t need more encouragement. She needs permission to be bad at something without it meaning she''s bad.'
WHERE id = '04f52c05-ad3b-421b-a17e-98f4068669cf';

-- Refatoração Script 4: Brushing teeth battle (INTENSE + Hygiene)
UPDATE scripts SET
  what_doesnt_work = E'You bought the soft-bristle brush. The bubblegum toothpaste. The two-minute timer with the little song.\n\nNone of it matters.\n\nThe moment that toothbrush approaches her mouth, she''s clenching. Backing into the corner. "IT BURNS. IT HURTS. I CAN''T."\n\nShe''s not lying. You can see it—the gag reflex when bristles touch her tongue, the way she squeezes her eyes shut like you''re hurting her.\n\nYou''ve tried making it fun (she threw the fun toothbrush). You''ve tried being firm (she held her mouth shut for eleven minutes). You''ve tried explaining cavities (she said she''d rather have no teeth).\n\nYou''ve tried doing it for her—she bit down.\n\nEvery night, same battle. By the end, both of you are exhausted, and her teeth are barely brushed anyway. You wonder if you''re traumatizing her over dental hygiene.',
  
  why_this_works = E'For some kids, toothbrushing isn''t unpleasant—it''s overwhelming. Their mouth has more nerve endings than almost any other body part, and hers are turned up to eleven.\n\nThe mint "flavor" isn''t refreshing. It''s fire. The bristles aren''t soft. They''re sandpaper. And asking her to tolerate this while standing still, not spitting too early, and being timed? It''s sensory torture with an audience.\n\nThis script works because it gives her back control over the overwhelming input. She chooses the pressure. She picks when to start. She decides what she can handle tonight.\n\nIt''s not about lowering standards—it''s about building tolerance. A child who brushes her front teeth calmly tonight will be able to handle more tomorrow. A child who''s forced to brush everything while crying will dread it forever.'
WHERE id = '295a0fec-7be9-40dc-9b57-d8f9591753c1';