// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// ✅ SECURITY: Use environment variables - NO hardcoded fallbacks
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL!;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY!;

export const SUPABASE_CONFIG_ERROR_MESSAGE =
  'As variáveis VITE_SUPABASE_URL e VITE_SUPABASE_PUBLISHABLE_KEY precisam ser configuradas nos Secrets do projeto Lovable.';

// Validate environment variables
if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  console.error('❌ Configuração Supabase ausente:', {
    VITE_SUPABASE_URL: SUPABASE_URL ? '✅ Configurada' : '❌ Ausente',
    VITE_SUPABASE_PUBLISHABLE_KEY: SUPABASE_PUBLISHABLE_KEY ? '✅ Configurada' : '❌ Ausente'
  });
  throw new Error(SUPABASE_CONFIG_ERROR_MESSAGE);
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const isSupabaseConfigured = true;

// Note: Using 'any' for compatibility with existing codebase
// TODO: Migrate to proper Database typing incrementally
export const supabase = createClient<any>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});